#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="${CONFIG:-$ROOT/config/rpc-tunnel.env}"

if [[ ! -f "$CONFIG" ]]; then
  CONFIG="$ROOT/config/rpc-tunnel.example.env"
fi

source "$CONFIG"

LOCAL_REDPANDA_BROKER_PORT="${LOCAL_REDPANDA_BROKER_PORT:-${LOCAL_KAFKA_PORT:-19092}}"
LOCAL_INFERENCE_PORT="${LOCAL_INFERENCE_PORT:-${LOCAL_QWEN_INFERENCE_PORT:-18200}}"

: "${RPC_HOST:?set RPC_HOST}"
: "${RPC_PORT:?set RPC_PORT}"
: "${RPC_USER:?set RPC_USER}"
: "${REMOTE_TUNNEL_HOST:?set REMOTE_TUNNEL_HOST}"
: "${LOCAL_REDPANDA_BROKER_PORT:?set LOCAL_REDPANDA_BROKER_PORT}"
: "${LOCAL_PANDAPROXY_PORT:?set LOCAL_PANDAPROXY_PORT}"
: "${LOCAL_TYPESENSE_PORT:?set LOCAL_TYPESENSE_PORT}"
: "${LOCAL_QDRANT_PORT:?set LOCAL_QDRANT_PORT}"
: "${LOCAL_CLICKHOUSE_HTTP_PORT:?set LOCAL_CLICKHOUSE_HTTP_PORT}"
: "${LOCAL_NORMALIZER_PORT:?set LOCAL_NORMALIZER_PORT}"
: "${LOCAL_INFERENCE_PORT:?set LOCAL_INFERENCE_PORT}"
: "${REMOTE_REDPANDA_BROKER_PORT:?set REMOTE_REDPANDA_BROKER_PORT}"
: "${REMOTE_PANDAPROXY_PORT:?set REMOTE_PANDAPROXY_PORT}"
: "${REMOTE_TYPESENSE_PORT:?set REMOTE_TYPESENSE_PORT}"
: "${REMOTE_QDRANT_PORT:?set REMOTE_QDRANT_PORT}"
: "${REMOTE_CLICKHOUSE_HTTP_PORT:?set REMOTE_CLICKHOUSE_HTTP_PORT}"
: "${REMOTE_NORMALIZER_PORT:?set REMOTE_NORMALIZER_PORT}"
: "${REMOTE_INFERENCE_PORT:?set REMOTE_INFERENCE_PORT}"

exec ssh -N \
  -p "$RPC_PORT" \
  -L "${LOCAL_REDPANDA_BROKER_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_REDPANDA_BROKER_PORT}" \
  -L "${LOCAL_PANDAPROXY_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_PANDAPROXY_PORT}" \
  -L "${LOCAL_TYPESENSE_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_TYPESENSE_PORT}" \
  -L "${LOCAL_QDRANT_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_QDRANT_PORT}" \
  -L "${LOCAL_CLICKHOUSE_HTTP_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_CLICKHOUSE_HTTP_PORT}" \
  -L "${LOCAL_NORMALIZER_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_NORMALIZER_PORT}" \
  -L "${LOCAL_INFERENCE_PORT}:${REMOTE_TUNNEL_HOST}:${REMOTE_INFERENCE_PORT}" \
  "${RPC_USER}@${RPC_HOST}"
